# Generated by Django 2.1.3 on 2018-11-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeta',
            name='id_swapi',
            field=models.IntegerField(null=True),
        ),
    ]
